export const Types = {
  NEW_TODO: "NEW_TODO",
  TOGGLE_COMPLETED_TODO: "TOGGLE_COMPLETED_TODO",
  SELECT_COLOR: "SELECT_COLOR",
  DELETE_TODO: "DELETE_TODO",
  CLEAR_TODO: "CLEAR_TODO",
  FILTER_TODO: "FILTER_TODO",
  NEW_COLOR_FILTER: "NEW_COLOR_FILTER",
  REMOVE_COLOR_FILTER: "REMOVE_COLOR_FILTER",
  MARK_ALL_TODO: "MARK_ALL_TODO",
};
